apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: postgres
  name: data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: data
spec:
  ports:
    - name: pg
      nodePort: 31005
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgresql
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgresql
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - args:
            - -c
            - |
              max_connections=500
          env:
            - name: APP_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /data/$(APP_POD_NAME)
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          image: postgres:12.7-alpine
          imagePullPolicy: IfNotPresent
          name: postgres
          ports:
            - containerPort: 5432
              name: pg
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - mountPath: /data
              name: datadir
      volumes:
        - hostPath:
            path: /sharedfs/postgresql
            type: DirectoryOrCreate
          name: datadir
