apiVersion: v1
data:
  DATABASE_URL: postgresql://postgres:@postgres.data:5432/ethereum?ssl=false
  MIX_ENV: prod
kind: ConfigMap
metadata:
  labels:
    app: pg-migrate
  name: postgres-migrate-env-config
  namespace: data
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: pg-migrate
  name: postgres-migrate-job
  namespace: data
spec:
  template:
    metadata:
      labels:
        app: pg-migrate
    spec:
      containers:
      - args:
        - -c
        - |
          mix do ecto.create && \
          mix do ecto.migrate
        command:
        - /bin/sh
        envFrom:
        - configMapRef:
            name: postgres-migrate-env-config
        image: vyeve/blockscout:v0.0.1
        imagePullPolicy: IfNotPresent
        name: worker
      restartPolicy: OnFailure
