apiVersion: v1
kind: Namespace
metadata:
  name: eth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-services
  namespace: eth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: micro-registry
  namespace: eth
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - patch
      - watch
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-registry
  namespace: eth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: micro-registry
subjects:
  - kind: ServiceAccount
    name: micro-services
    namespace: eth
