apiVersion: v1
data:
  BLOCK_TRANSFORMER: clique
  COIN: ETH
  DATABASE_URL: postgresql://postgres:@postgres.data:5432/ethereum?ssl=false
  ETHEREUM_JSONRPC_HTTP_URL: http://eth-node-service.eth.svc.cluster.local:8545
  ETHEREUM_JSONRPC_TRACE_URL: ws://eth-node-service.eth.svc.cluster.local:8546
  ETHEREUM_JSONRPC_VARIANT: geth
  ETHEREUM_JSONRPC_WS_URL: ws://eth-node-service.eth.svc.cluster.local:8546
  MIX_ENV: prod
  POOL_SIZE: "100"
  WS_BLOCK_PERIOD: "120000"
kind: ConfigMap
metadata:
  labels:
    app: blockscout
  name: blockscout-env-config
  namespace: eth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockscout
  name: blockscout-service
  namespace: eth
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4000
      nodePort: 31003
  selector:
    app: blockscout
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blockscout
  name: blockscout-service
  namespace: eth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockscout
  template:
    metadata:
      labels:
        app: blockscout
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockscout
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - phx.server
          command:
            - mix
          envFrom:
            - configMapRef:
                name: blockscout-env-config
          image: vyeve/blockscout:v0.0.1
          imagePullPolicy: IfNotPresent
          name: service
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
